### ISSUE TITLE
create student

### ISSUE THREAD

**Issue by mohammedafeef** [tinkerhubemea/students-profile#5]
* personal details
* educational details
* family details

**Comment by mohammedafeef** [comment]
- [ true]

**Comment by mohammedafeef** [comment]
- [ ]

**Comment by mohammedafeef** [comment]
- [ ] dljfl

**Comment by nahyansharvin** [comment]
- [x] Personal Details
- [x] Educational Details
- [x] Family Details

Above pages UI completed.

**Comment by nahyansharvin** [comment]
* Student add page custom components added.
* Same address and guardian radio button added.
* Dependencies page added.
* Form state updated.
* Form validation yet to be done.

Resolved in #13

**Comment by mohammedafeef** [comment]
> * Student add page custom components added.
> * Same address and guardian radio button added.
> * Dependencies page added.
> * Form state updated.
> * Form validation yet to be done.
> 
> Resolved in #13

reviewed and merged to master

**Comment by nahyansharvin** [comment]
* Student details page form validation done.
* Error state set.
* Error message fixed.

Resolved in #14
